on:
  pull_request:
    branches:
      - development

jobs:
  test-and-code-quality:
    name: 🧪 Test and Linters
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.24'

      - name: Get dependencies
        run: |
          cd api
          go mod download

      - name: golangci-lint
        uses: golangci/golangci-lint-action@v8
        with:
          version: v2.1.6
          args: --timeout 8m
          working-directory: api

      - name: Test
        run: |
          cd api
          export APP_ENV=test
          go test ./... -v -short -coverprofile packageWithpbgo.cov -coverpkg=./...
          grep -vE '^gofr\.dev\/.*\.pb\.go' packageWithpbgo.cov > profile.cov
          go tool cover -func profile.cov
          go tool cover -func profile.cov | grep total | awk '{print "Coverage: " $3}'
